permalink: /:year:month:day/:title
url: "https://easy-day.github.io/"
baseurl: ""

# variables
name: easy-day?
description: easy-day란 무엇일까?
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true