permalink: /:year:month:day/:title
url: "https://easy-day.github.io/"
baseurl: ""

# variables
name: 해킹에 철학을 담다_JIHUN_Blog
description: JIHUN_Blog
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
